config/routes.rb
Rails.application.routes.draw do

  resources :periods, :candidatures, :municipalities, :parties, :candidates do
    collection do
      get 'buscar'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "candidatures#menu"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/candidate.rb
class Candidate < ApplicationRecord
    validates :identification, presence: { message: "El campo de identificación es obligatorio" }
    validates :name, presence: { message: "El nombre es obligatorio" }
end

app/models/candidature.rb
class Candidature < ApplicationRecord
  validates :codeInscription, presence: { message: "El campo de código es obligatorio" }
  validates :dateInscription, presence: { message: "El campo de fecha es obligatorio" }
  validates :candidate_id, presence: { message: "El campo de candidato es obligatorio" }
  validates :municipality_id, presence: { message: "El campo de municipio es obligatorio" }
  validates :period_id, presence: { message: "El campo de periodo es obligatorio" }

  belongs_to :candidate
  belongs_to :municipality
  belongs_to :period
  has_many :candidature_parties
  has_many :parties, through: :candidature_parties
end

app/models/candidature_party.rb
class CandidatureParty < ApplicationRecord
    belongs_to :candidature
    belongs_to :party
end

app/models/municipality.rb
class Municipality < ApplicationRecord
    validates :daneCode, presence: { message: "El campo de código es obligatorio" }
    validates :name, presence: { message: "El nombre es obligatorio" }
end

app/models/party.rb
class Party < ApplicationRecord
    validates :identification, presence: { message: "El campo de identificación es obligatorio" }
    validates :name, presence: { message: "El nombre es obligatorio" }

    has_many :candidature_parties
    has_many :candidatures, through: :candidature_parties
end

app/models/period.rb
class Period < ApplicationRecord
    validates :start_year, presence: { message: "El año de inicio es obligatorio" }
    validates :end_year, presence: { message: "El año de fin es obligatorio" }

    def display_name
        "#{start_year} - #{end_year}"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_candidate, only: %i[ show ]

  def index
  end

  def show
  end

  def buscar
    @parametro = params[:parametro]
    @candidate = Candidate.find_by(identification: @parametro)

    if @candidate
      render 'show'
    else
      redirect_to candidates_path
    end
  end

  def new
    @candidate = Candidate.new
  end

  def create
    @candidate = Candidate.new(candidate_params)

    respond_to do |format|
      if @candidate.save
        format.html { redirect_to candidate_url(@candidate) }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_candidate
      @candidate = Candidate.find(params[:id])
    end

    def candidate_params
      params.require(:candidate).permit(:identification, :name)
    end
end

app/controllers/candidatures_controller.rb
class CandidaturesController < ApplicationController
  before_action :set_candidature, only: %i[ show ]

  def index
  end

  def show
  end

  def buscar
    @parametro = params[:parametro]
    @candidature = Candidature.find_by(codeInscription: @parametro)

    if @candidature
      render 'show'
    else
      redirect_to candidatures_path
    end
  end

  def new
    @candidature = Candidature.new
  end

  def create
    @candidature = Candidature.new(candidature_params)

    respond_to do |format|
      if @candidature.save
        parties = params[:candidature][:party_ids].reject(&:blank?)

        parties.each do |party_id|
          @candidature_parties = CandidatureParty.create(candidature_id: @candidature.id, party_id: party_id)
        end

        @candidature = Candidature.includes(:parties).find(@candidature.id)
        format.html { redirect_to candidature_url(@candidature) }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end


  private
    def set_candidature
      @candidature = Candidature.includes(:parties).find(params[:id])
    end

    def candidature_params
      params.require(:candidature).permit(:codeInscription, :dateInscription, :candidate_id, :municipality_id, :period_id, :party_ids)
    end
end

app/controllers/municipalities_controller.rb
class MunicipalitiesController < ApplicationController
  before_action :set_municipality, only: %i[ show ]

  def index
  end

  def show
  end

  def buscar
    @parametro = params[:parametro]
    @municipality = Municipality.find_by(daneCode: @parametro)

    if @municipality
      render 'show'
    else
      redirect_to municipalities_path
    end
  end

  def new
    @municipality = Municipality.new
  end

  def create
    @municipality = Municipality.new(municipality_params)

    respond_to do |format|
      if @municipality.save
        format.html { redirect_to municipality_url(@municipality)}
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_municipality
      @municipality = Municipality.find(params[:id])
    end

    def municipality_params
      params.require(:municipality).permit(:daneCode, :name)
    end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_action :set_party, only: %i[ show ]

  def index
  end

  def show
  end

  def buscar
    @parametro = params[:parametro]
    @party = Party.find_by(identification: @parametro)

    if @party
      render 'show'
    else
      redirect_to parties_path
    end
  end

  def new
    @party = Party.new
  end

  def create
    @party = Party.new(party_params)

    respond_to do |format|
      if @party.save
        format.html { redirect_to party_url(@party) }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_party
      @party = Party.find(params[:id])
    end

    def party_params
      params.require(:party).permit(:identification, :name)
    end
end

app/controllers/periods_controller.rb
class PeriodsController < ApplicationController
  before_action :set_period, only: %i[ show ]

  def index
  end

  def show
  end

  def buscar
    @parametro = params[:parametro]
    @period = Period.find_by(start_year: @parametro)

    if @period
      render 'show'
    else
      redirect_to periods_path
    end
  end

  def new
    @period = Period.new
  end

  def create
    @period = Period.new(period_params)

    respond_to do |format|
      if @period.save
        format.html { redirect_to period_url(@period)}
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_period
      @period = Period.find(params[:id])
    end

    def period_params
      params.require(:period).permit(:start_year, :end_year)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/candidatures_helper.rb
module CandidaturesHelper
end

app/helpers/municipalities_helper.rb
module MunicipalitiesHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/views/candidates/_candidate.html.erb
<div id="<%= dom_id candidate %>">
  <div class="flex flex-col text-sm justify-start flex-wrap gap-2">
    <div class="flex flex-row flex-wrap gap-2">
      <span class="font-medium">Identificación:</span>
      <%= candidate.identification %>
    </div>
    <div class="flex flex-row flex-wrap gap-2">
      <span class="font-medium">Nombre:</span>
      <%= candidate.name %>
    </div>
  </div>
</div>

app/views/candidates/_form.html.erb
<%= form_with(model: candidate, class: 'overflow-auto pb-[5dvh] text-sm flex justify-center') do |form| %>
  <div class="inline">
    <div class="my-5">
      <%= form.label "Identificación" %>
      <%= form.text_field :identification, class: "block text-sm shadow rounded-md border border-gray-400 outline-none px-3 py-2 w-full", placeholder: 'Cedula de ciudadanía' %>
      <div class="text-red-500 mt-1">
        <%= candidate.errors.full_messages_for(:identification).join(', ').split[1..-1].join(" ") if candidate.errors[:identification].any? %>
      </div>
    </div>
    <div class="my-5">
      <%= form.label "Nombre completo" %>
      <%= form.text_field :name, class: "block text-sm shadow rounded-md border border-gray-400 outline-none px-3 py-2 w-full", placeholder: 'Nombre del candidato' %>
      <div class="text-red-500 mt-1">
        <%= candidate.errors.full_messages_for(:name).join(', ').split[1..-1].join(" ") if candidate.errors[:name].any? %>
      </div>
    </div>
    <%= form.submit "Crear candidato", class: "rounded-lg py-2 px-5 bg-blue-600 text-white inline-block font-medium hover:brightness-105 cursor-pointer" %>
    <%= link_to "Volver al inicio", candidates_path, class: "ml-2 py-2 border border-gray-300 bg-[#e3e3e3] hover:brightness-105 rounded-lg px-5 bg-gray-100 inline-block font-medium" %>
  </div>
<% end %>

app/views/candidates/index.html.erb
<div class="relative w-screen h-screen flex items-center justify-center text-sm">
  <div class="border bg-[#fefefe] border-gray-300 w-11/12 lg:w-1/2 h-1/2 drop-shadow-xl rounded-lg p-4">
    <div class="w-full">
      <div class="relative my-5">
        <h1 class="font-bold text-center text-2xl my-2 underline">Registro de candidatos a elección de alcaldes</h1>
        <h1 class="font-bold text-center text-base mb-2">Candidatos</h1>
      </div>
      <div class="w-full flex flex-wrap justify-center gap-4 h-full">
        <div class="flex flex-col items-center flex-wrap justify-center gap-3 font-medium">
          <span>1. Buscar candidato:</span>
          <%= form_tag(buscar_candidates_path, method: :get, class:'flex justify-start flex-col gap-2') do %>
            <%= text_field_tag :parametro, params[:parametro], placeholder: 'Buscar por identificación', class:"w-full text-sm rounded-lg py-2" %>
            <%= submit_tag "Buscar", class: "hover:brightness-105 rounded-lg py-2 px-5 bg-blue-600 text-white font-medium cursor-pointer" %>
          <% end %>
        </div>
        <div class="flex flex-col flex-wrap justify-start items-center gap-3 font-medium">
          <span>2. Crear nuevo candidato:</span>
          <%= link_to "Nuevo candidato", new_candidate_path, class: "flex text-center items-center rounded-lg py-2 px-12 hover:brightness-105 bg-blue-600 w-auto text-white block font-medium" %>
        </div>
      </div>
      <div class="flex items-center justify-center pt-10">
        <%= link_to "Volver al menu", root_path, class: "ml-2 py-2 border border-gray-300 bg-[#e3e3e3] hover:brightness-105 rounded-lg px-5 bg-gray-100 inline-block font-medium" %>
      </div>
    </div>
  </div>
</div>

app/views/candidates/new.html.erb
<div class="mx-auto md:w-2/3 w-full text-center flex flex-col justify-center p-5">
  <h1 class="font-bold text-4xl">Nuevo candidato</h1>
  <div class="text-left">
    <%= render "form", candidate: @candidate %>
  </div>
</div>

app/views/candidates/show.html.erb
<div class="w-screen h-screen">
  <div class="w-full h-full flex flex-col justify-center items-center">
    <div class="w-1/2 h-1/2 mx-auto flex-col border boder-gray-200 shadow-xl">
      <div class="w-full p-4">
        <h1 class="text-2xl text-center underline">Resumen candidato</h1>
        <div class="flex flex-col justify-start gap-4 my-5">
          <%= render @candidate %>
        </div>
      </div>
      <div class="flex items-center justify-center">
        <%= link_to "Volver al inicio", candidates_path, class: "ml-2 py-2 border border-gray-300 bg-[#e3e3e3] hover:brightness-105 rounded-lg px-5 bg-gray-100 inline-block font-medium" %>
      </div>
    </div>
  </div>
</div>

app/views/candidatures/_candidature.html.erb
<div id="<%= dom_id candidature %>">
  <div class="flex flex-col text-sm justify-start flex-wrap gap-2">
    <div class="flex flex-row flex-wrap gap-2">
      <span class="font-medium">Código de inscripción:</span>
      <%= candidature.codeInscription %>
    </div>
    <div class="flex flex-row flex-wrap gap-2">
      <span class="font-medium">Fecha de inscripción:</span>
      <%= candidature.dateInscription %>
    </div>
    <div class="flex flex-row flex-wrap gap-2">
      <span class="font-medium">Municipio:</span>
      <%= candidature.municipality.name %>
    </div>
    <div class="flex flex-row flex-wrap gap-2">
      <span class="font-medium">Candidato:</span>
      <%= candidature.candidate.name %>
    </div>
    <div class="flex flex-col flex-wrap gap-2">
      <span class="font-medium">Partidos:</span>
      <div class="flex flex-col pl-2">
        <% @candidature.parties.each_with_index do |party, index| %>
          <ul>
            <li><%= "#{index + 1}. #{party.name}" %></li>
          </ul>
        <% end %>
      </div>
    </div>
    <div class="flex flex-row flex-wrap gap-2">
      <span class="font-medium">Periodo:</span>
      <%= candidature.period.display_name %>
    </div>
  </div>
</div>

app/views/candidatures/_form.html.erb
<%= form_with(model: candidature, class: 'overflow-auto pb-[5dvh] text-sm flex justify-center') do |form| %>
  <div class="inline">
    <div class="my-5">
      <%= form.label "Código de inscripción" %>
      <%= form.text_field :codeInscription, class: "block text-sm shadow rounded-md border border-gray-400 outline-none px-3 py-2 w-full", placeholder: 'Código' %>
      <div class="text-red-500 mt-1">
        <%= candidature.errors.full_messages_for(:codeInscription).join(', ').split[1..-1].join(" ") if candidature.errors[:codeInscription].any? %>
      </div>
    </div>
    <div class="my-5">
      <%= form.label "Fecha de inscripción", class: "block mt-3 mb-1" %>
      <%= form.date_field :dateInscription, as: :date, class: 'block shadow rounded-md border border-gray-400 outline-none px-3 py-2 w-full' %>
      <div class="text-red-500 mt-1">
        <%= candidature.errors.full_messages_for(:dateInscription).join(', ').split[1..-1].join(" ") if candidature.errors[:dateInscription].any? %>
      </div>
    </div>
    <div class="my-5">
      <%= form.label "Candidato" %>
      <%= form.collection_select :candidate_id, Candidate.all.order(name: :asc), :id, :name, { prompt: 'Seleccione un candidato' }, { class: 'block shadow-md rounded-md border border-gray-400 outline-none px-3 py-2 w-full', required:true } %>
      <div class="text-red-500 mt-1">
        <%= candidature.errors.full_messages_for(:candidate_id).join(', ').split[1..-1].join(" ") if candidature.errors[:candidate_id].any? %>
      </div>
    </div>
    <div class="my-5">
      <%= form.label "Periodo" %>
      <%= form.collection_select :period_id, Period.select(:id, :start_year, :end_year), :id, :display_name, { prompt: 'Seleccione un periodo' }, { class: 'block shadow-md rounded-md border border-gray-400 outline-none px-3 py-2 w-full', required: true } %>
      <div class="text-red-500 mt-1">
        <%= candidature.errors.full_messages_for(:period_id).join(', ').split[1..-1].join(" ") if candidature.errors[:period_id].any? %>
      </div>
    </div>
    <div class="my-5">
      <%= form.label "Municipio" %>
      <%= form.collection_select :municipality_id, Municipality.all.order(name: :asc), :id, :name, { prompt: 'Seleccione un municipio' }, { class: 'block shadow-md rounded-md border border-gray-400 outline-none px-3 py-2 w-full', required:true } %>
      <div class="text-red-500 mt-1">
        <%= candidature.errors.full_messages_for(:municipality_id).join(', ').split[1..-1].join(" ") if candidature.errors[:municipality_id].any? %>
      </div>
    </div>
    <div class="my-5">
      <%= form.label "Partidos" %>
      <%= form.collection_select :party_ids, Party.all.order(name: :asc), :id, :name, {  }, { class: 'block shadow-md rounded-md border border-gray-400 outline-none px-3 py-2 w-full', required: true, multiple: true } %>
      <div class="text-red-500 mt-1">
        <%= candidature.errors.full_messages_for(:party_ids).join(', ').split[1..-1].join(" ") if candidature.errors[:party_ids].any? %>
      </div>
    </div>
    <%= form.submit "Crear candidatura", class: "rounded-lg py-2 px-5 bg-blue-600 text-white inline-block font-medium hover:brightness-105 cursor-pointer" %>
    <%= link_to "Volver al inicio", candidatures_path, class: "ml-2 py-2 border border-gray-300 bg-[#e3e3e3] hover:brightness-105 rounded-lg px-5 bg-gray-100 inline-block font-medium" %>
  </div>
<% end %>

app/views/candidatures/index.html.erb
<div class="relative w-screen h-screen flex items-center justify-center text-sm">
  <div class="border bg-[#fefefe] border-gray-300 w-11/12 lg:w-1/2 h-1/2 drop-shadow-xl rounded-lg p-4">
    <div class="w-full">
      <div class="relative my-5">
        <h1 class="font-bold text-center text-2xl my-2 underline">Registro de candidatos a elección de alcaldes</h1>
        <h1 class="font-bold text-center text-base mb-2">Candidaturas</h1>
      </div>
      <div class="w-full flex flex-wrap justify-center gap-4 h-full">
        <div class="flex flex-col items-center flex-wrap justify-center gap-3 font-medium">
          <span>1. Buscar candidatura:</span>
          <%= form_tag(buscar_candidatures_path, method: :get, class:'flex justify-start flex-col gap-2') do %>
            <%= text_field_tag :parametro, params[:parametro], placeholder: 'Buscar por inscripción', class:"w-full text-sm rounded-lg py-2" %>
            <%= submit_tag "Buscar", class: "hover:brightness-105 rounded-lg py-2 px-5 bg-blue-600 text-white font-medium cursor-pointer" %>
          <% end %>
        </div>
        <div class="flex flex-col flex-wrap justify-start items-center gap-3 font-medium">
          <span>2. Crear nueva candidatura:</span>
          <%= link_to "Nueva candidatura", new_candidature_path, class: "flex text-center items-center rounded-lg py-2 px-12 hover:brightness-105 bg-blue-600 w-auto text-white block font-medium" %>
        </div>
      </div>
      <div class="flex items-center justify-center pt-10">
        <%= link_to "Volver al menu", root_path, class: "ml-2 py-2 border border-gray-300 bg-[#e3e3e3] hover:brightness-105 rounded-lg px-5 bg-gray-100 inline-block font-medium" %>
      </div>
    </div>
  </div>
</div>

app/views/candidatures/menu.html.erb
<% nav_link_classes = 'flex justify-between text-left items-center py-1 px-6 align-middle text-gray-600 no-underline rounded-lg py-2 px-5 bg-blue-600 shadow-lg text-white inline-block font-medium hover:brightness-125 cursor-pointer md:py-2' %>
<div class="relative w-screen h-screen flex items-center justify-center text-sm">
  <div class="border bg-[#fefefe] border-gray-300 w-11/12 lg:w-1/2 h-1/2 drop-shadow-xl rounded-lg p-4">
    <div class="w-full">
      <div class="relative my-5">
        <h1 class="font-bold text-center text-2xl my-2 underline">Registro de candidatos a elección de alcaldes</h1>
        <h1 class="font-bold text-center text-base mb-2">Menú principal</h1>
      </div>
      <div class="w-full flex flex-wrap justify-center gap-5 h-full">
        <div class="flex flex-col items-center flex-wrap justify-center gap-2 font-medium">
          <span>1. Gestión de candidatos</span>
          <%= link_to candidates_path, class: "#{nav_link_classes}" do %>
            Gestionar
          <% end %>
        </div>
        <div class="flex flex-col items-center flex-wrap justify-center gap-2 font-medium">
          <span>2. Gestión de municipios</span>
          <%= link_to municipalities_path, class: "#{nav_link_classes}" do %>
            Gestionar
          <% end %>
        </div>
        <div class="flex flex-col items-center flex-wrap justify-center gap-2 font-medium">
          <span>3. Gestión de periodos</span>
          <%= link_to periods_path, class: "#{nav_link_classes}" do %>
            Gestionar
          <% end %>
        </div>
        <div class="flex flex-col items-center flex-wrap justify-center gap-2 font-medium">
          <span>4. Gestión de candidaturas</span>
          <%= link_to candidatures_path, class: "#{nav_link_classes}" do %>
            Gestionar
          <% end %>
        </div>
        <div class="flex flex-col items-center flex-wrap justify-center gap-2 font-medium">
          <span>5. Gestión de partidos</span>
          <%= link_to parties_path, class: "#{nav_link_classes}" do %>
            Gestionar
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/candidatures/new.html.erb
<div class="mx-auto md:w-2/3 w-full text-center flex flex-col justify-center p-5">
  <h1 class="font-bold text-4xl">Nuevo candidatura</h1>
  <div class="text-left">
    <%= render "form", candidature: @candidature %>
  </div>
</div>

app/views/candidatures/show.html.erb
<div class="w-screen h-screen">
  <div class="w-full h-full flex flex-col justify-center items-center">
    <div class="w-1/2 h-1/2 mx-auto flex-col border boder-gray-200 shadow-xl">
      <div class="w-full p-4">
        <h1 class="text-2xl text-center underline">Resumen candidatura</h1>
        <div class="flex flex-col justify-start gap-4 my-5">
          <%= render @candidature %>
        </div>
      </div>
      <div class="flex items-center justify-center">
        <%= link_to "Volver al inicio", candidatures_path, class: "ml-2 py-2 border border-gray-300 bg-[#e3e3e3] hover:brightness-105 rounded-lg px-5 bg-gray-100 inline-block font-medium" %>
      </div>
    </div>
  </div>
</div>

app/views/municipalities/index.html.erb
<div class="relative w-screen h-screen flex items-center justify-center text-sm">
  <div class="border bg-[#fefefe] border-gray-300 w-11/12 lg:w-1/2 h-1/2 drop-shadow-xl rounded-lg p-4">
    <div class="w-full">
      <div class="relative my-5">
        <h1 class="font-bold text-center text-2xl my-2 underline">Registro de candidatos a elección de alcaldes</h1>
        <h1 class="font-bold text-center text-base mb-2">Municipios</h1>
      </div>
      <div class="w-full flex flex-wrap justify-center gap-4 h-full">
        <div class="flex flex-col items-center flex-wrap justify-center gap-3 font-medium">
          <span>1. Buscar municipio:</span>
          <%= form_tag(buscar_municipalities_path, method: :get, class:'flex justify-start flex-col gap-2') do %>
            <%= text_field_tag :parametro, params[:parametro], placeholder: 'Buscar por código', class:"w-full text-sm rounded-lg py-2" %>
            <%= submit_tag "Buscar", class: "hover:brightness-105 rounded-lg py-2 px-5 bg-blue-600 text-white font-medium cursor-pointer" %>
          <% end %>
        </div>
        <div class="flex flex-col flex-wrap justify-start items-center gap-3 font-medium">
          <span>2. Crear nuevo municipio:</span>
          <%= link_to "Nuevo municipio", new_municipality_path, class: "flex text-center items-center rounded-lg py-2 px-12 hover:brightness-105 bg-blue-600 w-auto text-white block font-medium" %>
        </div>
      </div>
      <div class="flex items-center justify-center pt-10">
        <%= link_to "Volver al menu", root_path, class: "ml-2 py-2 border border-gray-300 bg-[#e3e3e3] hover:brightness-105 rounded-lg px-5 bg-gray-100 inline-block font-medium" %>
      </div>
    </div>
  </div>
</div>

app/views/municipalities/new.html.erb
<div class="mx-auto md:w-2/3 w-full text-center flex flex-col justify-center p-5">
  <h1 class="font-bold text-4xl">Nuevo municipio</h1>
  <div class="text-left">
    <%= render "form", municipality: @municipality %>
  </div>
</div>

app/views/parties/index.html.erb
<div class="relative w-screen h-screen flex items-center justify-center text-sm">
  <div class="border bg-[#fefefe] border-gray-300 w-11/12 lg:w-1/2 h-1/2 drop-shadow-xl rounded-lg p-4">
    <div class="w-full">
      <div class="relative my-5">
        <h1 class="font-bold text-center text-2xl my-2 underline">Registro de candidatos a elección de alcaldes</h1>
        <h1 class="font-bold text-center text-base mb-2">Partidos</h1>
      </div>
      <div class="w-full flex flex-wrap justify-center gap-4 h-full">
        <div class="flex flex-col items-center flex-wrap justify-center gap-3 font-medium">
          <span>1. Buscar partido:</span>
          <%= form_tag(buscar_parties_path, method: :get, class:'flex justify-start flex-col gap-2') do %>
            <%= text_field_tag :parametro, params[:parametro], placeholder: 'Buscar por identificacion', class:"w-full text-sm rounded-lg py-2" %>
            <%= submit_tag "Buscar", class: "hover:brightness-105 rounded-lg py-2 px-5 bg-blue-600 text-white font-medium cursor-pointer" %>
          <% end %>
        </div>
        <div class="flex flex-col flex-wrap justify-start items-center gap-3 font-medium">
          <span>2. Crear nuevo partido:</span>
          <%= link_to "Nuevo municipio", new_party_path, class: "flex text-center items-center rounded-lg py-2 px-12 hover:brightness-105 bg-blue-600 w-auto text-white block font-medium" %>
        </div>
      </div>
      <div class="flex items-center justify-center pt-10">
        <%= link_to "Volver al menu", root_path, class: "ml-2 py-2 border border-gray-300 bg-[#e3e3e3] hover:brightness-105 rounded-lg px-5 bg-gray-100 inline-block font-medium" %>
      </div>
    </div>
  </div>
</div>

app/views/periods/index.html.erb
<div class="relative w-screen h-screen flex items-center justify-center text-sm">
  <div class="border bg-[#fefefe] border-gray-300 w-11/12 lg:w-1/2 h-1/2 drop-shadow-xl rounded-lg p-4">
    <div class="w-full">
      <div class="relative my-5">
        <h1 class="font-bold text-center text-2xl my-2 underline">Registro de candidatos a elección de alcaldes</h1>
        <h1 class="font-bold text-center text-base mb-2">Periodos</h1>
      </div>
      <div class="w-full flex flex-wrap justify-center gap-4 h-full">
        <div class="flex flex-col items-center flex-wrap justify-center gap-3 font-medium">
          <span>1. Buscar periodo:</span>
          <%= form_tag(buscar_periods_path, method: :get, class:'flex justify-start flex-col gap-2') do %>
            <%= text_field_tag :parametro, params[:parametro], placeholder: 'Buscar por año de inicio', class:"w-full text-sm rounded-lg py-2" %>
            <%= submit_tag "Buscar", class: "hover:brightness-105 rounded-lg py-2 px-5 bg-blue-600 text-white font-medium cursor-pointer" %>
          <% end %>
        </div>
        <div class="flex flex-col flex-wrap justify-start items-center gap-3 font-medium">
          <span>2. Crear nuevo periodo:</span>
          <%= link_to "Nuevo periodo", new_period_path, class: "flex text-center items-center rounded-lg py-2 px-12 hover:brightness-105 bg-blue-600 w-auto text-white block font-medium" %>
        </div>
      </div>
      <div class="flex items-center justify-center pt-10">
        <%= link_to "Volver al menu", root_path, class: "ml-2 py-2 border border-gray-300 bg-[#e3e3e3] hover:brightness-105 rounded-lg px-5 bg-gray-100 inline-block font-medium" %>
      </div>
    </div>
  </div>
</div>